name: Terraform Destroy
on:
  workflow_dispatch:

jobs:    
  terraform_destroy:
    runs-on: ubuntu-latest
    env:
     TF_VAR_DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
     TF_VAR_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}      
     aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}       
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts         

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}      
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1        

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init  -reconfigure

      - name: Apply changes to production
        run:  terraform destroy -auto-approve  
