name: Terraform plan
on:
  push:
    branches:
      - main

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      TF_VAR_DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      TF_VAR_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

  Terraform_plan:
    needs: vars
    uses: mahadikbs/reusable-workflows/.github/workflows/terraform-plan.yaml@main      
    with:
      TF_VARDOCKER_USERNAME: ${{needs.vars.TF_VAR_DOCKER_USERNAME}}
      TF_VAR_DOCKER_PASSWORD: ${{needs.vars.TF_VAR_DOCKER_PASSWORD}}
      environment: test
      runner: ubuntu-latest

    secrets: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}  
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SSH_PUBLIC_KEY: ${{secrets.SSH_PUBLIC_KEY}}
