name: Terraform apply
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    
jobs: 
  Build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install docker
        run: |
          chmod +x db/docker.sh
          ./db/docker.sh

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      # - name: Login to DockerHub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t k8s-prom-grafana .

      - name: Push Image to DockerHub
        run: docker tag k8s-prom-grafana myrepo/k8s-prom-grafana:latest
      - run: docker push myrepo/k8s/prom-grafana:latest

  Terraform_apply:
    uses: mahadikbs/reusable-workflows/.github/workflows/terraform-apply.yaml@main
    with:
      environment: production
      runner: ubuntu-latest
      TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}       
      
    secrets: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}  
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SSH_PUBLIC_KEY: ${{secrets.SSH_PUBLIC_KEY}}
      TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}      


  